version: '3'

services: 
  proxy_front:
    image: 'nginx:1.12.2-alpine' 
    container_name: test_proxy
    restart: unless-stopped
    ports: 
      - '8088:80'
    volumes: 
      - '/root/dockers/proxy-test/www:/usr/share/nginx/html'       
      - '/root/dockers/proxy-test/conf/site.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - test_server

  www1:
    image: 'nginx:1.12.2' 
    container_name: test_www1
    restart: unless-stopped
    #ports: 
    #  - '9081:80'
    volumes: 
      - '/root/dockers/proxy-test/www1:/usr/share/nginx/html'       
    networks:
      - test_server
  
  www2:
    image: 'nginx:1.12.2' 
    container_name: test_www2
    restart: unless-stopped
    #ports: 
    #  - '9082:80'
    volumes: 
      - '/root/dockers/proxy-test/www2:/usr/share/nginx/html'       
    networks:
      - test_server

  www3:
    image: 'nginx:1.12.2' 
    container_name: test_www3
    restart: unless-stopped
    expose:
      - 80
    volumes: 
      - '/root/dockers/proxy-test/www3:/usr/share/nginx/html'       
    networks:
      - test_server
  
  www4:
    image: 'nginx:1.12.2' 
    container_name: test_www4
    restart: unless-stopped
    ports: 
      - '9084:80'
    volumes: 
      - '/root/dockers/proxy-test/www4:/usr/share/nginx/html'       
    networks:
      - test_server

networks: 
  test_server: 
    driver: bridge
